apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: app-container
      image: node:18
      env:
        - name: APP_PORT
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: APP_PORT
              optional: false
          
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: DB_HOST
              optional: false

        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: DB_PORT
              optional: false

        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: DB_DATABASE
              optional: false

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: DB_USER
              optional: false

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: DB_PASSWORD
              optional: false

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: DATABASE_URL
              optional: false
              
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: JWT_SECRET
              optional: false

        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: JWT_EXPIRATION
              optional: false

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: AWS_ACCESS_KEY_ID
              optional: false

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: AWS_SECRET_ACCESS_KEY
              optional: false

        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: app-env-secret
              key: REGION
              optional: false
  restartPolicy: Never
