apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  
  #////
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: crawan/intimacy-client:latest
          envFrom:
            - secretRef:
                name: app-env-secret
---
apiVersion: v1
kind: Service
metadata:
  name: intimacy-server-service
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000 